export const ACTION_SUCCESS_PRODUCTLIST = 'ACTION_SUCCESS_PRODUCTLIST'
export const ACTION_UNSUCCESS_PRODUCTLIST = 'ACTION_UNSUCCESS_PRODUCTLIST'

export const ACTION_SHOW_LOADING = 'ACTION_SHOW_LOADING';
export const ACTION_HIDE_LOADING = 'ACTION_HIDE_LOADING';
